# Site settings
title: OpenGov.se - Din ingång till värdeskapande genom transparens & öppenhet!
email: info@opengov.se
description: > # this means to ignore newlines until "baseurl:"
  Här hittar du information om projekt, aktiviteter och initiativ som gör Sverige till ett mer öppet samhälle med ökad transparens!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opengov.se" # the base hostname & protocol for your site
twitter_username: opengov_se
github_username:  okfse

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
